Import('project', 'libs')

project.StaticLibrary(
	target='tweedyCore',
	dirs=['core'],
	includes=['..'],
	libraries=[
		libs.boost,
		libs.boost_filesystem,
                libs.boost_signals,
                libs.boost_serialization,
		libs.gphoto2,
		]
	)
project.StaticLibrary(
	target='tweedyGui',
	dirs=['gui'],
	includes=['..'],
	libraries=[
		libs.tweedyCore,
		libs.qt4(
			uiFiles=project.scanFiles(['gui'],accept=['*.ui']),
			modules = [
				'QtCore',
				'QtOpenGL',
				'QtGui',
				'QtScript',
				'QtDeclarative',
				'QtXmlPatterns', # QML dependencies
				'QtNetwork', # QML dependencies
				'QtSvg', # QML dependencies
				'QtSql', # QML dependencies
				],
			),
		]
	)

tweedyApp = project.Program(
	target='tweedy',
	sources=['main.cpp'],
	includes=['..'],
	libraries=[
		libs.tweedyCore,
		libs.tweedyGui,
		]
	)


tweedyResources = Command( project.inOutputBin('resources'), '#resources', Copy('$TARGET', '$SOURCE') )

# tweedy application needs its resources
Depends( tweedyApp, tweedyResources )


