Import('project', 'libs')

project.StaticLibrary(
	target='tweedyCore',
	dirs=['core'],
	includes=['..'],
	libraries=[
		libs.boost,
		]
	)
project.StaticLibrary(
	target='tweedyGui',
	dirs=['gui'],
	includes=['..'],
	libraries=[
		libs.boost,
		libs.qt4(uiFiles=project.scanFiles(['gui'], accept=['*.ui'])),
		]
	)

project.Program(
	target='tweedy',
	sources=['main.cpp'],
	includes=['..'],
	libraries=[
		libs.tweedyCore,
		libs.tweedyGui,
		]
	)

